"""AgentBridgeProtocol — structural interface required by all Bridge*Mixin classes.

Every Bridge*Mixin inherits from this Protocol so mypy can resolve ``self.*``
attribute access without needing to know the concrete ``AgentBridge`` class at
definition time.  The Protocol lists only the attributes that mixins *use*;
``AgentBridge`` in ``core_bridge.py`` provides all concrete implementations.

PEP 544: a class that inherits ``Protocol`` (without ``@runtime_checkable``)
becomes a partial implementation — mypy resolves ``self.X`` against the declared
members, and the concrete class satisfies the protocol structurally.
"""

from __future__ import annotations

import threading
from concurrent.futures import ThreadPoolExecutor
from typing import Any, Callable, Protocol


class AgentBridgeProtocol(Protocol):
    """Structural interface shared by all AgentBridge mixin classes."""

    # ── Instance attributes set in AgentBridge.__init__ ──────────────────

    app: Any  # AgentApp — typed as Any to avoid circular import

    _bus: Any  # Old EventBus instance
    _typed_bus: Any  # New MessageBus instance (or None in mock mode)
    _typed_subscriptions: list[tuple[type, Any]]  # MessageBus subscriptions

    _orchestrator: Any  # Orchestrator | None
    _working_dir: str

    _agent_lock: threading.Lock
    _agent_running: bool
    _cancel_event: threading.Event
    _history_lock: threading.Lock
    history: list[tuple[str, str]]
    _pending_injections: list[str]
    _thread_pool: ThreadPoolExecutor

    _active_role: str
    _deferred_init_done: bool

    # _HISTORY_VERSION is a class-level constant on BridgeSessionMixin
    _HISTORY_VERSION: int

    # ── Methods that mixins call on ``self`` ──────────────────────────────

    def _subscribe_typed(self, event_cls: type, cb: Callable) -> None: ...
    def _post(self, msg: Any) -> None: ...
    def _schedule_callback(self, fn: Callable, *args: Any) -> None: ...

    # BridgeAgentMixin calls these on self:
    def _ensure_deferred_init(self) -> None: ...
    def _save_history(self) -> None: ...

    # BridgeSessionMixin calls these on self:
    def send_prompt(self, text: str) -> bool: ...
    def _publish_system_settings(self) -> None: ...
    def publish_session_new(self) -> None: ...
    def _publish_active_provider_status(self) -> None: ...
    def _check_provider_auth_on_startup(self) -> None: ...

    # BridgeContextMixin calls these on self:
    def _get_active_context_length(self) -> int: ...

    @staticmethod
    def _get_prompt_history_path() -> Any: ...  # returns Path

    # ── Event handler methods (defined across Bridge*Mixin classes) ───────
    # BridgeSubscriptionsMixin calls these via self.X; they are defined in the
    # other mixin classes and resolved at runtime via AgentBridge's MRO.

    def _on_system_settings(self, payload: dict) -> None: ...
    def _on_orchestrator_startup(self, payload: dict) -> None: ...
    def _on_provider_status(self, payload: dict) -> None: ...
    def _on_provider_unavailable(self, payload: dict) -> None: ...
    def _on_models_list(self, payload: dict) -> None: ...
    def _on_model_routing(self, payload: dict) -> None: ...
    def _on_model_response(self, payload: dict) -> None: ...
    def _on_model_token(self, payload: dict) -> None: ...
    def _on_stream_chunk(self, payload: dict) -> None: ...
    def _on_provider_context_window(self, payload: dict) -> None: ...
    def _on_tool_start(self, payload: dict) -> None: ...
    def _on_tool_finish(self, payload: dict) -> None: ...
    def _on_tool_error(self, payload: dict) -> None: ...
    def _on_diff_preview(self, payload: dict) -> None: ...
    def _on_file_modified(self, payload: dict) -> None: ...
    def _on_file_deleted(self, payload: dict) -> None: ...
    def _on_plan_progress(self, payload: dict) -> None: ...
    def _on_plan_requested(self, payload: dict) -> None: ...
    def _on_session_new(self, payload: dict) -> None: ...
    def _on_session_hydrated(self, payload: dict) -> None: ...
    def _on_session_health(self, payload: dict) -> None: ...
    def _on_ui_notification(self, payload: dict) -> None: ...
    def _on_log_new(self, payload: dict) -> None: ...
    def _on_token_budget(self, payload: dict) -> None: ...
    def _on_token_budget_warning(self, payload: dict) -> None: ...
    def _on_role_transition(self, payload: dict) -> None: ...
    def _on_preview_pending(self, payload: dict) -> None: ...
    def _on_git_branch(self, payload: dict) -> None: ...
    def _on_retry_attempt(self, payload: dict) -> None: ...
    def _on_retry_succeeded(self, payload: dict) -> None: ...
    def _on_retry_failed(self, payload: dict) -> None: ...
    def _on_context_degraded(self, payload: dict) -> None: ...
    def _on_context_compacted(self, payload: dict) -> None: ...
    def _on_task_queue_updated(self, payload: dict) -> None: ...
    def _on_step_start(self, payload: dict) -> None: ...
    def _on_step_finish(self, payload: dict) -> None: ...
    def _on_mcp_server_status(self, payload: dict) -> None: ...
    def _on_tool_permission_required(self, payload: dict) -> None: ...
    def _on_spawn_permission_required(self, payload: dict) -> None: ...
    def _on_usage_turn_summary(self, payload: dict) -> None: ...
    def _on_subagent_cost(self, payload: dict) -> None: ...
    def _on_doom_loop_detected(self, payload: dict) -> None: ...
    def _on_agent_message(self, payload: dict) -> None: ...
    def _on_delegation_start(self, payload: dict) -> None: ...
    def _on_delegation_finish(self, payload: dict) -> None: ...
