"""
Session Watcher - Health monitoring and automatic cleanup for agent sessions.

Provides:
- Automatic detection of stale/hung sessions
- Resource usage monitoring
- Automatic termination of failed sessions
- Health alerts and notifications
"""

import asyncio
import logging
import threading
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Callable, Any

logger = logging.getLogger(__name__)


class HealthStatus(Enum):
    """Session health status."""

    HEALTHY = "healthy"
    WARNING = "warning"  # Resource usage high
    STALE = "stale"  # No activity
    CRITICAL = "critical"  # Session may be hung
    FAILED = "failed"


@dataclass
class HealthReport:
    """Health status report for a session."""

    session_id: str
    status: HealthStatus
    last_active: float
    idle_time: float
    tool_call_count: int
    token_usage: int
    error_count: int
    issues: List[str] = field(default_factory=list)
    recommendations: List[str] = field(default_factory=list)


class AlertLevel(Enum):
    """Alert severity levels."""

    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


@dataclass
class SessionAlert:
    """Alert generated by the watcher."""

    alert_id: str
    session_id: str
    level: AlertLevel
    title: str
    message: str
    timestamp: float
    metadata: Dict[str, Any] = field(default_factory=dict)


class SessionWatcher:
    """
    Monitors session health and generates alerts.

    Features:
    - Automatic detection of stale sessions
    - Resource usage monitoring
    - Automatic cleanup of failed/stale sessions
    - Health alerts via callback system

    Usage:
        watcher = SessionWatcher()
        watcher.start()

        # Or use callbacks
        watcher.on_alert(lambda alert: print(f"ALERT: {alert.title}"))
    """

    _instance = None

    def __init__(
        self,
        stale_threshold: float = 300.0,  # 5 minutes
        critical_threshold: float = 600.0,  # 10 minutes
        max_tool_calls: int = 1000,
        max_token_usage: int = 100000,
        max_errors: int = 10,
    ):
        self.stale_threshold = stale_threshold
        self.critical_threshold = critical_threshold
        self.max_tool_calls = max_tool_calls
        self.max_token_usage = max_token_usage
        self.max_errors = max_errors

        # State
        self._running = False
        self._monitor_task: Optional[asyncio.Task] = None
        self._lock = threading.Lock()

        # Alert callbacks
        self._alert_callbacks: List[Callable[[SessionAlert], None]] = []

        # Alert history
        self._alert_history: List[SessionAlert] = []
        self._max_alert_history = 100

        # Auto-actions
        self._auto_cleanup_enabled = False
        self._auto_cleanup_on_critical = True

    @classmethod
    def get_instance(cls) -> "SessionWatcher":
        """Get the singleton instance."""
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    @classmethod
    def reset_instance(cls) -> None:
        """Reset the singleton (for testing)."""
        cls._instance = None

    def start(self) -> None:
        """Start the health monitoring loop."""
        if self._running:
            logger.warning("SessionWatcher already running")
            return

        self._running = True
        logger.info("Starting SessionWatcher")

        try:
            loop = asyncio.get_running_loop()
            self._monitor_task = loop.create_task(self._monitor_loop())
        except RuntimeError:
            logger.error("No event loop available for SessionWatcher")

    def stop(self) -> None:
        """Stop the health monitoring loop."""
        self._running = False
        if self._monitor_task:
            self._monitor_task.cancel()
            self._monitor_task = None
        logger.info("Stopped SessionWatcher")

    def on_alert(self, callback: Callable[[SessionAlert], None]) -> None:
        """Register a callback for alerts."""
        self._alert_callbacks.append(callback)

    def enable_auto_cleanup(self, enabled: bool = True) -> None:
        """Enable automatic cleanup of failed/stale sessions."""
        self._auto_cleanup_enabled = enabled
        logger.info(f"Auto cleanup enabled: {enabled}")

    async def _monitor_loop(self) -> None:
        """Main monitoring loop."""
        check_interval = 30.0  # Check every 30 seconds

        while self._running:
            try:
                await asyncio.sleep(check_interval)
                await self._check_all_sessions()
            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"Monitor loop error: {e}")

    async def _check_all_sessions(self) -> None:
        """Check health of all sessions."""
        try:
            from src.core.orchestration.session_registry import get_session_registry

            registry = get_session_registry()
            stats = registry.get_statistics()

            logger.debug(
                f"Session health check: {stats['total_sessions']} sessions, "
                f"{stats['stale_count']} stale"
            )

            # Check each session
            for info in registry._sessions.values():
                report = self._check_session_health(info)

                if report.status != HealthStatus.HEALTHY:
                    await self._handle_health_report(report)

        except Exception as e:
            logger.error(f"Error checking sessions: {e}")

    def _check_session_health(self, session_info) -> HealthReport:
        """Check health of a single session."""
        now = time.time()
        idle_time = now - session_info.last_active_at

        issues = []
        recommendations = []
        status = HealthStatus.HEALTHY

        # Check for staleness
        if idle_time > self.critical_threshold:
            status = HealthStatus.CRITICAL
            issues.append(f"Session stale for {idle_time:.0f}s (critical)")
            recommendations.append("Consider terminating this session")
        elif idle_time > self.stale_threshold:
            status = HealthStatus.STALE
            issues.append(f"Session stale for {idle_time:.0f}s")
            recommendations.append("Session may be waiting on external resource")

        # Check tool calls
        if session_info.tool_call_count >= self.max_tool_calls:
            status = HealthStatus.WARNING if status == HealthStatus.HEALTHY else status
            issues.append(f"High tool call count: {session_info.tool_call_count}")
            recommendations.append("Consider memory compaction")

        # Check token usage
        if session_info.token_usage >= self.max_token_usage:
            status = HealthStatus.WARNING if status == HealthStatus.HEALTHY else status
            issues.append(f"High token usage: {session_info.token_usage}")
            recommendations.append("Context may be approaching limit")

        # Check errors
        if session_info.error_count >= self.max_errors:
            status = HealthStatus.WARNING if status == HealthStatus.HEALTHY else status
            issues.append(f"High error count: {session_info.error_count}")
            recommendations.append("Review session errors")

        return HealthReport(
            session_id=session_info.session_id,
            status=status,
            last_active=session_info.last_active_at,
            idle_time=idle_time,
            tool_call_count=session_info.tool_call_count,
            token_usage=session_info.token_usage,
            error_count=session_info.error_count,
            issues=issues,
            recommendations=recommendations,
        )

    async def _handle_health_report(self, report: HealthReport) -> None:
        """Handle a health report, generating alerts as needed."""
        # Generate alert
        if report.status == HealthStatus.CRITICAL:
            alert = self._create_alert(
                session_id=report.session_id,
                level=AlertLevel.CRITICAL,
                title=f"Session {report.session_id} critical",
                message=f"Session idle for {report.idle_time:.0f}s",
            )
        elif report.status == HealthStatus.STALE:
            alert = self._create_alert(
                session_id=report.session_id,
                level=AlertLevel.WARNING,
                title=f"Session {report.session_id} stale",
                message=f"Session idle for {report.idle_time:.0f}s",
            )
        elif report.status == HealthStatus.WARNING:
            alert = self._create_alert(
                session_id=report.session_id,
                level=AlertLevel.WARNING,
                title=f"Session {report.session_id} resource warning",
                message=f"Tool calls: {report.tool_call_count}, Tokens: {report.token_usage}",
            )
        else:
            return

        self._emit_alert(alert)

        # Auto-cleanup if enabled
        if self._auto_cleanup_enabled and report.status == HealthStatus.STALE:
            await self._cleanup_stale_session(report.session_id)

    def _create_alert(
        self,
        session_id: str,
        level: AlertLevel,
        title: str,
        message: str,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> SessionAlert:
        """Create a new alert."""
        import uuid

        return SessionAlert(
            alert_id=str(uuid.uuid4())[:8],
            session_id=session_id,
            level=level,
            title=title,
            message=message,
            timestamp=time.time(),
            metadata=metadata or {},
        )

    def _emit_alert(self, alert: SessionAlert) -> None:
        """Emit an alert to all callbacks."""
        # Store in history
        with self._lock:
            self._alert_history.append(alert)
            if len(self._alert_history) > self._max_alert_history:
                self._alert_history = self._alert_history[-self._max_alert_history :]

        # Emit to callbacks
        for callback in self._alert_callbacks:
            try:
                callback(alert)
            except Exception as e:
                logger.error(f"Error in alert callback: {e}")

    async def _cleanup_stale_session(self, session_id: str) -> bool:
        """Attempt to cleanup a stale session."""
        try:
            from src.core.orchestration.session_registry import get_session_registry

            registry = get_session_registry()
            info = registry.get_session(session_id)

            if not info:
                return False

            # For child sessions (delegations), attempt cleanup
            if info.parent_session_id:
                logger.warning(
                    f"Auto-cleanup: terminating stale child session {session_id}"
                )
                registry.unregister_session(session_id, "Stale child session")
                return True

            return False

        except Exception as e:
            logger.error(f"Error cleaning up session {session_id}: {e}")
            return False

    def get_recent_alerts(
        self,
        session_id: Optional[str] = None,
        level: Optional[AlertLevel] = None,
        limit: int = 20,
    ) -> List[SessionAlert]:
        """Get recent alerts, optionally filtered."""
        with self._lock:
            alerts = self._alert_history.copy()

        if session_id:
            alerts = [a for a in alerts if a.session_id == session_id]

        if level:
            alerts = [a for a in alerts if a.level == level]

        return alerts[-limit:]

    def get_watcher_stats(self) -> Dict[str, Any]:
        """Get watcher statistics."""
        with self._lock:
            return {
                "running": self._running,
                "stale_threshold": self.stale_threshold,
                "critical_threshold": self.critical_threshold,
                "max_tool_calls": self.max_tool_calls,
                "max_token_usage": self.max_token_usage,
                "max_errors": self.max_errors,
                "alert_count": len(self._alert_history),
                "auto_cleanup_enabled": self._auto_cleanup_enabled,
            }


def get_session_watcher() -> SessionWatcher:
    """Get the global session watcher instance."""
    return SessionWatcher.get_instance()
