"""AgentAppProtocol — structural interface required by all AgentApp mixin classes.

Every App*Mixin, ChatDisplayMixin, and StatusBarMixin inherits from this Protocol
so mypy can resolve ``self.*`` attribute access without needing the concrete
``AgentApp`` class at definition time.  ``AgentApp`` in ``app.py`` provides all
concrete implementations.

PEP 544: a class that inherits ``Protocol`` (without ``@runtime_checkable``)
becomes a partial implementation — mypy resolves ``self.X`` against the declared
members, and the concrete class satisfies the protocol structurally.
"""

from __future__ import annotations

import collections
from pathlib import Path
from typing import Any, Callable, Literal, Optional, Protocol


class AgentAppProtocol(Protocol):
    """Structural interface shared by all AgentApp mixin classes."""

    # ── Textual App methods (provided by textual.app.App) ─────────────────

    def query_one(self, *args: Any, **kwargs: Any) -> Any: ...
    def query(self, selector: str) -> Any: ...
    def notify(self, message: str, *, title: str = ..., severity: Literal['information', 'warning', 'error'] = ..., timeout: float | None = ..., markup: bool = ...) -> None: ...
    def push_screen(self, screen: Any, *args: Any, **kwargs: Any) -> Any: ...
    def call_later(self, callback: Callable[..., Any], *args: Any, **kwargs: Any) -> bool: ...
    def post_message(self, message: Any) -> bool: ...

    # ── Textual reactive attributes ───────────────────────────────────────

    active_role: str
    total_tokens: int
    context_window: int
    pending_tasks: int
    queue_size: int
    is_streaming: bool
    agent_running: bool
    sub_title: str

    # ── Instance attributes set in AgentApp.__init__ ──────────────────────

    _bridge: Any  # AgentBridge — typed as Any to avoid circular import
    _session_id: str
    _current_stream: Any  # Optional[StreamView]
    _modified_files: list
    _settings: Any  # SettingsStore
    _last_task_text: str
    _tool_widgets: dict
    _tool_args: dict
    _subagent_widgets: dict
    _continue_state: Optional[dict]
    _pending_perm_count: int
    _allow_always_tools: set
    _queued_messages: collections.deque
    _queued_widget: Any
    _queued_message: Optional[str]
    _tool_call_count: int
    _session_input_tokens: int
    _session_output_tokens: int
    _at_picker_active: bool
    _at_picker_matches: Any  # list[str] in practice
    _at_picker_index: int
    _at_picker_widget: Any  # Optional[FilePickerOverlay]
    _at_prefix: str
    _at_file_cache: Any  # list[str]
    _at_file_cache_ts: float
    _palette_active: bool
    _palette_matches: Any  # list[str]
    _palette_index: int
    _worktree_mgr: Any
    _perm_tool_names: Any  # list[str]

    # ── Methods that mixins define and call on each other via self ─────────
    # (each is defined in one mixin but called from another via self.X)

    # StatusBarMixin
    def _update_status_bar(self) -> None: ...

    # ChatDisplayMixin — async methods
    def _mount_chat_widget(self, widget: Any) -> Any: ...
    def _prune_chat_log(self) -> None: ...
    def _finalize_stream(self) -> None: ...
    def _sched_chat_widget(self, widget: Any) -> None: ...
    def _ensure_stream_widget(self) -> Any: ...
    def _mount_and_scroll(self, widget: Any, container: Any) -> Any: ...
    def _expand_at_tokens(self, text: str) -> str: ...
    def _drain_message_queue(self) -> None: ...
    def _at_picker_hide(self) -> None: ...

    # AppSessionMixin / AppSlashCommandsMixin
    def _save_session_snapshot(self) -> None: ...
    def _clear_chat_panel(self) -> None: ...
    def _reset_sidebar(self) -> None: ...
    def _get_sessions_dir(self) -> Path: ...
    def _list_workspace_files(self, query: str = "", max_results: int = 30) -> list: ...

    # AppStatusHandlersMixin
    def _update_role_display(self, role: str) -> None: ...
    def _update_provider_status_widgets(self, *args: Any) -> None: ...
    def _update_status_text(self, text: str) -> None: ...
    def _update_mcp_status_chip(self, *args: Any) -> None: ...
    def _update_perm_badge(self, *args: Any) -> None: ...
    def _update_subagent_footer(self) -> None: ...

    # AppToolHandlersMixin / ChatDisplayMixin — async handlers
    def _chat_handle_plan_requested(self, event: Any) -> Any: ...

    # ChatDisplayMixin — all async, take a single event arg
    def _chat_handle_error(self, event: Any) -> Any: ...
    def _chat_handle_final_response(self, event: Any) -> Any: ...
    def _chat_handle_reasoning(self, event: Any) -> Any: ...
    def _chat_handle_session_health(self, event: Any) -> Any: ...
    def _chat_handle_stream_chunk(self, chunk: Any) -> Any: ...
    def _chat_handle_thinking_update(self, content: Any) -> Any: ...
    def _chat_handle_usage_turn_summary(self, *args: Any) -> Any: ...
    def _chat_handle_text_changed(self, *args: Any) -> Any: ...
    def _chat_handle_doom_loop(self, event: Any) -> Any: ...
    def _chat_handle_retry_attempt(self, event: Any) -> Any: ...
    def _chat_handle_retry_failed(self, event: Any) -> Any: ...
    def _chat_handle_retry_succeeded(self, event: Any) -> Any: ...
    def _chat_handle_context_compacted(self, event: Any) -> Any: ...
    def _chat_handle_context_degraded(self, event: Any) -> Any: ...

    # AppStatusHandlersMixin
    def action_open_sessions(self) -> None: ...
    def action_open_settings(self) -> None: ...
    def action_quit_app(self) -> None: ...

    # AppSlashCommandsMixin — slash handlers called via self.X dispatch
    def _slash_undo_with_confirm(self) -> Any: ...
    def _slash_fast(self) -> Any: ...
    def _slash_provider(self, args: str) -> Any: ...
    def _slash_model(self, args: str) -> Any: ...
    def _slash_diff(self) -> Any: ...
    def _slash_fork(self) -> Any: ...
    def _slash_share(self) -> Any: ...
    def _slash_rename(self, args: str) -> Any: ...
    def _slash_worktree(self, args: str) -> Any: ...
    def _slash_mcp(self, args: str) -> Any: ...
